apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: clarenceb/nginx-demo
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-demo-fs
          mountPath: /var/www/html
          subPath: web
      volumes:
      - name: nginx-demo-fs
        azureFile:
          secretName: azure-secret
          shareName: nginxdemoshare
          readOnly: true