version: '3'
services:
  nginx-api:
    image: nginx-demo
    ports:
      - "8081:80"
    volumes:
      - "./api:/var/www/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"

  nginx-web:
    image: nginx-demo
    ports:
      - "8082:80"
    volumes:
      - "./web:/var/www/html"

  nginx-web2:
    image: nginx-demo
    ports:
      - "8080:80"
    volumes:
      - "./web2:/var/www/html"
    depends_on:
      - nginx-api
