apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  containers:
  - name: nginx-demo
    image: clarenceb/nginx-demo:latest
    resources:
      limits:
        memory: "200Mi"
        cpu: 500m
      requests:
        memory: "100Mi"
        cpu: 100m