apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-demo-rs
  labels:
    app: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: clarenceb/nginx-demo